#!/usr/bin/env python3
"""Fill the <!--STATS_*--> placeholders in docs/report/*.md from docs/data.json.

Keeps the narrative hand-written and the numbers always current: rerun after
each scan and the report reflects the latest data instead of going stale.
"""
import json
import pathlib
import re
from collections import Counter

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / 'docs' / 'data.json').read_text())
OK = [p for p in DATA['plugins'] if p['level'] >= 0]
FLAGS = Counter(f['id'] for p in DATA['plugins'] for f in p.get('flags', []))
N = len(OK)


def pct(n):
    return f'{round(100 * n / N)}%' if N else '—'


def has(fid):
    return [p for p in OK if any(f['id'] == fid for f in p['flags'])]


def levels_block(zh=False):
    c = Counter(p['level'] for p in OK)
    strong = c[2] + c[3]
    head = ('| 等级 | 含义 | 数量 | 占比 |\n|---|---|---|---|\n' if zh else
            '| Level | Meaning | Count | Share |\n|---|---|---|---|\n')
    labels = ({3: '强能力 + 敏感行为', 2: '强能力(其一)', 1: '常规', 0: '无显著能力面'} if zh else
              {3: 'Powerful + sensitive behavior', 2: 'Powerful (one of)', 1: 'Ordinary', 0: 'No notable surface'})
    rows = ''.join(f'| **C{l}** | {labels[l]} | {c[l]} | {pct(c[l])} |\n' for l in (3, 2, 1, 0))
    tail = (f'\n**{pct(strong)} 的插件带强能力面(C2+),{pct(c[3])} 同时存在敏感行为(C3)。**\n'
            if zh else
            f'\n**{pct(strong)} of scanned plugins carry a powerful capability surface (C2+); '
            f'{pct(c[3])} combine it with sensitive behavior (C3).**\n')
    return head + rows + tail


def patch_block(zh=False):
    n = len(has('runtime_patch'))
    ex = sorted(has('runtime_patch'), key=lambda p: -p['stars'])[:5]
    lst = '\n'.join(f'- [{p["repo"]}](https://github.com/{p["repo"]}) — {p["stars"]:,}★' for p in ex)
    if zh:
        return (f'**{n} 个插件({pct(n)})通过 `manifest.bundle.patch` 给 dsh 运行时本体打补丁。**\n\n'
                f'星标最高的几个:\n\n{lst}\n')
    return (f'**{n} plugins ({pct(n)}) patch the dsh runtime itself via `manifest.bundle.patch`.**\n\n'
            f'The most-starred among them:\n\n{lst}\n')


def token_block(zh=False):
    n = len(has('token_env'))
    if zh:
        return (f'**{n} 个插件({pct(n)})读取凭证类环境变量**(名称含 KEY/TOKEN/SECRET/PASSWORD 等),'
                f'涉及 AWS、阿里云 OSS、GitHub、各家模型 API 等。\n')
    return (f'**{n} plugins ({pct(n)}) read credential-class environment variables** '
            f'(names containing KEY/TOKEN/SECRET/PASSWORD), spanning AWS, Aliyun OSS, GitHub, '
            f'and several model-provider APIs.\n')


def footer(zh=False):
    top = ', '.join(f'`{k}` {v}' for k, v in FLAGS.most_common(6))
    date = DATA['generated_at'][:10]
    if zh:
        return (f'*数据快照:{date} · 扫描 {N} / {DATA["total"]} 个仓库 · '
                f'高频标志:{top}*\n\n*本报告由 [dsh-xray](https://github.com/unStone/dsh-xray) 生成,'
                f'数字随每日扫描自动更新。*')
    return (f'*Data snapshot: {date} · {N} of {DATA["total"]} repositories scanned · '
            f'Top flags: {top}*\n\n*Generated by [dsh-xray](https://github.com/unStone/dsh-xray); '
            f'figures refresh with the daily scan.*')


def render(path, zh):
    text = path.read_text()
    for marker, fn in (('STATS_LEVELS', levels_block), ('STATS_PATCH', patch_block),
                       ('STATS_TOKEN', token_block), ('FOOTER', footer)):
        text = re.sub(rf'<!--{marker}-->.*?<!--/{marker}-->',
                      lambda _: f'<!--{marker}-->\n{fn(zh)}<!--/{marker}-->', text, flags=re.S)
        text = text.replace(f'<!--{marker}-->\n<!--/{marker}-->', '')
        if f'<!--{marker}-->' in text and f'<!--/{marker}-->' not in text:
            text = text.replace(f'<!--{marker}-->', f'<!--{marker}-->\n{fn(zh)}<!--/{marker}-->')
    path.write_text(text)
    print(f'rendered {path.name} (N={N})')


if __name__ == '__main__':
    for name, zh in (('2026-08.md', False), ('2026-08.zh.md', True)):
        p = ROOT / 'docs' / 'report' / name
        if p.exists():
            render(p, zh)
